name: SANDYFEIHUANG
favicon: null
layout_spectrum: 0.8344098273664713
typography_spectrum: 0.9614044432528317
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8083006294909865
  lightness: 0.1251809319946915
  saturation: 0.4174431134015322
  rhythmicContrast: 0.8190449697431177
purpose: []
